# Generated by Django 5.1.3 on 2024-11-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
