# Generated by Django 5.1.3 on 2024-11-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_seller_signup_alter_kyc_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_signup',
            name='category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
