# Generated by Django 5.1.1 on 2024-11-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_alter_seller_signup_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_signup',
            name='file',
        ),
    ]
