# Generated by Django 5.1.1 on 2024-11-17 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_remove_seller_signup_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_signup',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/seller_files/'),
        ),
        migrations.AlterField(
            model_name='seller_signup',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='seller_signup',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seller_signup',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='seller_signup',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='seller_signup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='seller_signup',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='seller_signup',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('admin_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='Backend.seller_signup')),
            ],
        ),
    ]
