# Generated by Django 5.1.1 on 2024-11-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_remove_seller_signup_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_signup',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/seller_files/'),
        ),
        migrations.AlterField(
            model_name='seller_signup',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='seller_signup',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seller_signup',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='seller_signup',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='seller_signup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='seller_signup',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='seller_signup',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
