# Generated by Django 5.1.1 on 2024-11-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_remove_product_additional_images_remove_product_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory_management',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
    ]
