# Generated by Django 5.1.3 on 2024-11-22 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_remove_users_id_alter_users_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='pwd',
            new_name='password',
        ),
    ]
