# Generated by Django 5.1.1 on 2024-12-06 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=10)),
                ('user_type', models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('Seller', 'Seller'), ('Customer', 'Customer')], max_length=255)),
                ('is_status', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('is_status', models.BooleanField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='SellerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussiness_name', models.CharField(max_length=100)),
                ('bussiness_address', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='seller_details')),
                ('bussiness_mobile_no', models.CharField(max_length=10)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_status', models.BooleanField()),
                ('slug', models.SlugField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('product_description', models.TextField(blank=True, max_length=100)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.FloatField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('inventory_status', models.CharField(default='In Stock', max_length=50)),
                ('low_stock_alert', models.BooleanField(default=False)),
                ('is_physical', models.BooleanField(default=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('weight_unit', models.CharField(default='kg', max_length=10)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('requires_shipping', models.BooleanField(default=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('main_image', models.ImageField(upload_to='products/images/')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('return_policy', models.TextField(blank=True, null=True)),
                ('warranty', models.TextField(blank=True, null=True)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='account.subcategory')),
            ],
        ),
    ]
