# Generated by Django 5.1.3 on 2024-11-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=10)),
                ('user_type', models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('Seller', 'Seller'), ('Customer', 'Customer')], max_length=255)),
                ('is_status', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
