# Generated by Django 5.1.1 on 2024-12-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_product_category_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdetail',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
