# Generated by Django 5.0 on 2024-12-08 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_category_id_subcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory_id',
            new_name='subcategory',
        ),
    ]
