# Generated by Django 5.1.1 on 2024-12-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_user_type1_alter_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='approval_status',
            new_name='status',
        ),
    ]
