# Generated by Django 5.1.1 on 2024-12-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_product_seller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_id',
            new_name='category',
        ),
    ]
