# Generated by Django 5.1.1 on 2024-12-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_category_id_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
