# Generated by Django 5.1.1 on 2024-12-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_product_admin_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='admin_approve',
            field=models.CharField(default='admin_request', max_length=20),
        ),
    ]
